CBMEMORY_SOURCE_DIRECTORY := src
CBMEMORY_INCLUDE_DIRECTORY := include
CBMEMORY_BUILD_DIRECTORY := build
CBMEMORY_BINARY_DIRECTORY := bin
CBMEMORY_EXAMPLES_DIRECTORY := examples

CBMEMORY_SOURCE_FILES =
CBMEMORY_EXAMPLES_FILES =

CBMEMORY_OBJECT_FILES = $(patsubst $(CBMEMORY_SOURCE_DIRECTORY)/%.cpp, $(CBMEMORY_BUILD_DIRECTORY)/src/%.o, $(CBMEMORY_SOURCE_FILES))

CBMEMORY_EXAMPLES_OBJECT_FILES = $(patsubst $(CBMEMORY_EXAMPLES_DIRECTORY)/%.cpp, $(CBMEMORY_BUILD_DIRECTORY)/examples/%.o, $(CBMEMORY_EXAMPLES_FILES))